apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webportal
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: webportal
    server: 'https://kubernetes.default.svc'
  source:
    path: gitops
    repoURL: 'https://github.com/andrewlinuxadmin/ocp-virt-gitops.git'
    targetRevision: main
  sources: []
  project: default
