kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crb-sa-cluster-admin-aap
subjects:
  - kind: ServiceAccount
    name: sa-cluster-admin-aap
    namespace: aap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

